### ISSUE TITLE
QUESTION: [If I subscribe will the nagging request go away?]

### ISSUE THREAD

**Issue by qdt2k2** [MarkIvanDev/JumpPoint#3]
I actually did and it is still showing every time a new window is open. It is annoying and killing the workflow.
Plus one-time purchase would be a cool option.

**Comment by MarkIvanDev** [comment]
I am sorry that this has disrupted your workflow. In the coming update, the notification will default to closed when a new window is opened. One-time purchase subscription will also be taken into consideration for a future update. Thank you for your feedback!
